In [1]:
import json
import os
import pandas

In [2]:
exps = []
for file in os.listdir("./experiment"):
    with open(os.path.join("./experiment",file)) as f:
        model,_,adaptername,dataset = file.split('-')
        dataset = dataset.split('.')[0]
        exps.append((json.loads(f.read()),model,adaptername,dataset))
anss = []
for obj_ in exps:
    obj,model,adaptername,dataset = obj_
    all_ = len(obj)
    currnt = len([c for c in obj if c['flag']])
    anss.append({
        "acc":currnt/all_,
        "dataset":dataset,
        "adapter":adaptername,
    })


df = pandas.DataFrame(anss).sort_values(by="dataset" , ascending=True) 
df

         acc     dataset        adapter
17  0.181102        AQuA         kvlora
7   0.177165        AQuA  prototypelora
13  0.181102        AQuA           lora
15  0.425316      AddSub  prototypelora
4   0.032911      AddSub         kvlora
11  0.032911      AddSub           lora
1   0.031667  MultiArith           lora
16  0.031667  MultiArith         kvlora
10  0.451667  MultiArith  prototypelora
3   0.027000       SVAMP         kvlora
14  0.027000       SVAMP           lora
6   0.248000       SVAMP  prototypelora
8   0.027559    SingleEq           lora
2   0.444882    SingleEq  prototypelora
12  0.027559    SingleEq         kvlora
9   0.018954       gsm8k           lora
5   0.018954       gsm8k         kvlora
0   0.185747       gsm8k  prototypelora